### ISSUE TITLE
Safari 10.1 crash "TypeError: undefined is not a constructor (evaluating 'new i')"

### ISSUE THREAD

**Issue by jehna** [webcomponents/webcomponentsjs#750] opened 2017-03-29 12:16 UTC
# Description

Safari 10.1 crashes to webcomponentsjs' error:

```
TypeError: undefined is not a constructor (evaluating 'new i')
HTMLElement — custom-elements-es5-adapter.js:4:295
PropertyAccessors — data:text/javascript;charset=utf-8,var…%0A:113:133
TemplateStamp — data:text/javascript;charset=utf-8,var…%0A:450:125
PropertyEffects — data:text/javascript;charset=utf-8,var…%0A:1194:125
PolymerElement — data:text/javascript;charset=utf-8,var…%0A:532:127
MyApplication — data:text/javascript;charset=utf-8,var…%0A:15:117
define
Global Code — data:text/javascript;charset=utf-8,var…%0A:33
```

# How to reproduce

1. Clone repository https://github.com/jehna/polymer-webcomponentjs-safari-crash-bug
2. Install dependencies, build & run the project
3. Open the page with Safari 10.1

## Behaviour

The page randomly crashes (about once in five reloads or so) with Safari 10.1 to the following error:

```
TypeError: undefined is not a constructor (evaluating 'new i')
HTMLElement — custom-elements-es5-adapter.js:4:295
PropertyAccessors — data:text/javascript;charset=utf-8,var…%0A:113:133
TemplateStamp — data:text/javascript;charset=utf-8,var…%0A:450:125
PropertyEffects — data:text/javascript;charset=utf-8,var…%0A:1194:125
PolymerElement — data:text/javascript;charset=utf-8,var…%0A:532:127
MyApplication — data:text/javascript;charset=utf-8,var…%0A:15:117
define
Global Code — data:text/javascript;charset=utf-8,var…%0A:33
```

## Expected behaviour

The page should not crash with Safari 10.1

**Comment by FredKSchott** [comment] 2017-03-31 00:36
Hmm, I can't reproduce in your repo even after ton of refreshes (v10.0, v10.1, or v10.2).

In the past, we've seen this exact problem on earlier versions of polymer-cli, but it was fixed in the latest release. Can you just confirm that you're on the latest version of polymer-cli@next (0.18.0-pre.15)?

**Comment by Artur-** [comment] 2017-03-31 09:08
I see this also in our project with Safari 10.1. 

The window.HTMLElement function in custom-elements-es5-adapter.js
```
        window.HTMLElement = function() {
            if (!f) {
                const h = d.get(this.constructor),
                    i = c.call(window.customElements, h);
                g = !0;
                const j = new i;
                return j
            }
            f = !1;
        }
```
is only called when `f==true` when everything works, but every now and then, it is called when `f==false` and the if block is actually executed (and fails at `new i` with the described error)

When I see it, the call originates from
```
  customElements.define('dom-module', DomModule);
```

Not sure how to debug it further

**Comment by jehna** [comment] 2017-03-31 09:28
Yes, I can confirm that `polymer-cli` is version `0.18.0-pre.15`.

If you build the project with `npm run build`, it should automatically use the version from the `node_modules/` directory that is fixed to `0.18.0-pre.15`. I also have `0.18.0-pre.15` installed globally on my machine.

Here's a video of the issue:

https://www.youtube.com/watch?v=f-9GFxWaN6o

I'm using macOS Sierra.

**Comment by FredKSchott** [comment] 2017-04-03 18:07
Alright, thanks for the extra info. We'll make time to dig into this this week.

/cc @justinfagnani who has the most experience with `custom-elements-es5-adapter.js`

**Comment by justinfagnani** [comment] 2017-04-03 18:10
I'm taking a look over the next couple of days as I can. The non-determinism is funny, and it's either a race that I didn't consider, or a bug in Safari.

**Comment by justinfagnani** [comment] 2017-04-06 00:22
So this repro is using the webcomponents-loader, which we just deprecated last week in favor of `custom-elements-es5-adapter.js`. Directly including `custom-elements-es5-adapter.js` is exactly supposed to fix this error, so I believe this bug should be fixed now.

**Comment by jehna** [comment] 2017-04-06 06:35
@justinfagnani if you build the project, the `polymer-cli` inserts the following script element to the `index.html` file:

```
<script src="/bower_components/webcomponentsjs/custom-elements-es5-adapter.js"></script>
```

So please revisit this bug with the following instructions to properly build & run the project:

```
git clone https://github.com/jehna/polymer-webcomponentjs-safari-crash-bug
cd polymer-webcomponentjs-safari-crash-bug
npm install
bower install
npm run build
npm run start
open http://localhost:8081/
```

**Comment by arthurevans** [comment] 2017-04-06 19:11
@justinfagnani We deprecated `webcomponents-loader`? Was that what you meant to say, because it's the first I've heard of it, and there's no sign of said deprecation on the webcomponentsjs repo.

**Comment by FredKSchott** [comment] 2017-04-06 19:45
@arthurevans I believe @justinfagnani meant `webcomponents-es5-loader.js`, which was removed  in favor of `custom-elements-es5-adapter.js` (automatically injected by build, if needed) + `webcomponents-es5-loader.js`

**Comment by FredKSchott** [comment] 2017-04-06 19:45
@arthurevans I believe @justinfagnani meant `webcomponents-es5-loader.js`, which was removed in favor of` custom-elements-es5-adapter.js` (automatically injected by build, if needed) + `webcomponents-loader.js`

**Comment by jehna** [comment] 2017-04-26 09:03
@justinfagnani any updates?

**Comment by yanne** [comment] 2017-04-26 09:10
I also get this error using `"Polymer/polymer#2.0.0-rc.7"` and `"webcomponents/webcomponentsjs#v1.0.0-rc.11"`

**Comment by alvarezguille** [comment] 2017-04-26 10:34
So can I when serving compiled version to safari 10.1.
Non compiled works as expected.

**Comment by Haprog** [comment] 2017-04-26 12:40
Interesting issue. I tried reloading a simple Polymer 2 app compiled to ES5 with Safari 10.1 and first encountered this problem on ~8th reload and second time after 27 more reloads.

**Comment by CaptainCodeman** [comment] 2017-04-27 17:46
It's also happening for me fairly regularly - Safari 10.1, no Polymer, just an es6 -> es5 compiled web-component and the es5 shim + wc loader (as `polymer cli` would add them to the body).

Safari 10.1 seems pretty unstable, I'm getting "Send to Apple" crash reports quite frequently.

**Comment by CaptainCodeman** [comment] 2017-04-28 03:46
hmmn, if I just embed the `custom-elements-es5-adapter.js` contents *into* the `index.html` page, it all seems to work fine with no issues, or at least without those issues.

The reason for the script-loading switcheroo was for IE11, right? because the adapter has to have the arrow function for some reason (?)

**Comment by CaptainCodeman** [comment] 2017-04-28 05:10
Apologies for the noise but it turns out that while embedding it in the page _reduced_ how often it occurred, it didn't actually prevent it entirely.

After littering the code with console.log statements, it's behavior when it fails truly is bizarre - like the surrounding statements are skipped or made async.

**Comment by mraerino** [comment] 2017-05-02 02:23
I just encountered this problem.
Happens really often though. About every second time.
Funnily much fewer if developer tools are open.

**Comment by CaptainCodeman** [comment] 2017-05-03 00:58
The only consistent approach I've found to running with Safari is to serve es6 to it, which means either differential serving or a fragment of JS to chose which version to load, e.g.:

```html
<script src="/bower_components/webcomponentsjs/webcomponents-loader.js" async></script>
<script>
  var s = document.createElement('script');
  try {
    eval('"use strict"; class foo {}');
    s.src = '/dist/element.es6.js';
  } catch (e) {
    s.src = '/dist/element.es5.js';
  }
  document.head.appendChild(s);
</script>
```

**Comment by mraerino** [comment] 2017-05-07 13:01
@CaptainCodeman this is a really nice way to do feature-detection. Was such a drag to do it on the server. Thanks for this snippet! ✨

**Comment by TimvdLippe** [comment] 2018-06-17 15:50
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!

**Closed by TimvdLippe** 2018-06-17 15:50 UTC
