### ISSUE TITLE
IE11 - SCRIPT445: Object doesn't support this action

### ISSUE THREAD

**Issue by hyyan** [webcomponents/webcomponentsjs#790] opened 2017-05-23 12:53 UTC
Hello , 

**[IE 11 Only]**
I am getting the following error from `webcomponents-lite.js (150,316)`  after building the polymer-start-kit with polymer-cli@1.0.0 

Any idea how to resolve this?
Thanks in advance

**Comment by robertwbradford** [comment] 2017-05-23 15:40
I'm getting a similar error in IE11 when including `<script src="/polyfills/webcomponentsjs/webcomponents-loader.js"></script>` directly in an HTML document:
```
SCRIPT438: Object doesn't support property or method 'includes'
File: webcomponents-lite.js, Line: 150, Column: 316
```

**Comment by hyyan** [comment] 2017-05-30 07:03
Any news about this one ?!!

**Comment by ajbarriosleon** [comment] 2017-06-12 09:45
Hello! I faced a migration from Polymer 1.x to a hybrid component and I got the same error on IE11. I hope this comment floats that issue.

**Comment by ronnyroeller** [comment] 2017-06-13 21:28
Did you check that the JavaScript is actually compiled to ES5?

See also: https://www.polymer-project.org/2.0/docs/es6

**Comment by hyyan** [comment] 2017-06-14 09:22
@ronnyroeller 100% sure it is compiled correctly, I checked the build files

**Comment by neonexus** [comment] 2017-06-26 21:06
I've got the exact same problem, trying to build a web widget. Said widget obviously needs to be cross-browser compatible, and this is holding up my work; been pulling my hair out for a few hours now. 

Stupid IE...

**Comment by thomasd** [comment] 2017-07-03 13:54
I had the same error with polymer-start-kit (polymer-cli@1.1.0) in IE11. Not only when building the app but also when served with `polymer serve`. I nailed down the issue to this line in my-app.html:

`this.rootPattern = (new URL(this.rootPath)).pathname;`

IE11 has only basic support for the URL-API (see https://developer.mozilla.org/de/docs/Web/API/URL). 
I solved this issue by including an url-polyfill in my projects index.html.
 I used this one https://www.npmjs.com/package/@publica/url-polyfill .
Although I think other implementations should work fine.

No everything is working for me in IE11. :)

**Comment by Westbrook** [comment] 2017-07-10 15:16
@azakus the solution above by @thomasd works like a charm. Does this look like a change that could make the main library as dependency or possibly the two uses of `new URL` could be removed for simpler code or? It's only IE, so probably makes best sense to get it included on the side somehow, which might imply it belongs in template applications (i.e. PSK2 around the point of `<script>if (!window.customElements) { document.write('<!--'); }</script>`) but not sure what would be "best" here...

**Comment by abdonrd** [comment] 2017-07-27 18:03
The last version of the PSK doesn't use the `new URL()` anymore.

**Comment by juicelink** [comment] 2017-08-17 13:00
same error (SCRIPT445) with webcomponents-sd-ce.js
works with 1.0.0-rc.6 but not further

error thrown in @webcomponents/shadydom/src/patch-events.js

**Comment by arthurevans** [comment] 2017-10-06 16:47
@juicelink Do you have the `new URL` line in your app shown in https://github.com/webcomponents/webcomponentsjs/issues/790#issuecomment-312651915 above? This line was included in some versions of the PSK, but has been removed from newer versions of the PSK.

The `URL` class shouldn't be used in the Polymer library itself.

**Comment by arthurevans** [comment] 2017-10-06 16:53
The root cause here appears to be the PSK issue, https://github.com/PolymerElements/polymer-starter-kit/issues/1025, which has been resolved. Closing this, please comment here if you believe you're still seeing this issue.

**Comment by arthurevans** [comment] 2017-10-06 16:54
Hm. Apparently I can't close it. @azakus plz close?

**Closed** 2017-10-06 17:10 UTC

**Comment by juicelink** [comment] 2017-10-06 17:49
I don't use PSK , working with skatejs
