### ISSUE TITLE
"Uncaught TypeError: Illegal constructor" when extending other native elements

### ISSUE THREAD

**Issue by robertwbradford** [webcomponents/webcomponentsjs#778] opened 2017-05-05 23:44 UTC
I'm getting a `Uncaught TypeError: Illegal constructor` error when trying to extend something other than `HTMLElement`:

```html
<template>
    <style>
        :host {
            background-color: gray;
        }
    </style>
    <b>I'm in shadow dom!</b>
    <slot></slot>
</template>

<script>
    class MyForm extends HTMLFormElement {
        constructor() {
            super();

            // Attach a shadow root to the element.
            const template = document.currentScript.ownerDocument.querySelector('template');
            this.attachShadow({mode: `open`}).appendChild(template.content.cloneNode(true), true);
        }
    }

    customElements.define('my-form', MyForm, {extends: 'form'});
</script>
```

If I extend `HTMLElement` it works fine. The example on https://developers.google.com/web/fundamentals/getting-started/primers/customelements#extendhtml is also not working.

Does this polyfill seek to solve this?

**Comment by notwaldorf** [comment] 2017-05-10 06:14
This is happening because native element extension (`is=`) is no longer supported in the v1 spec, and the polyfill does not implement it either

**Comment by bedeoverend** [comment] 2017-05-10 06:46
@robertwbradford follow along with [this PR](https://github.com/webcomponents/custom-elements/pull/88) for when `is=` will be supported in the Polyfill

**Comment by robertwbradford** [comment] 2017-05-10 14:56
Ok, thank you. I also came across https://github.com/w3c/webcomponents/issues/509 after posting here. Lively debate!

**Comment by TimvdLippe** [comment] 2018-07-03 10:43
Closing this as duplicate of https://github.com/webcomponents/custom-elements/issues/13

**Closed by TimvdLippe** 2018-07-03 10:43 UTC

**Comment by Mohib008** [comment] 2019-03-14 14:56
jQuery.Deferred exception: Illegal constructor TypeError: Illegal constructor , i am stack over here how to fix it ?
