### ISSUE TITLE
polyfill <link rel="stylesheet" type="text/css">

### ISSUE THREAD

**Issue by etm** [webcomponents/webcomponentsjs#400] opened 2015-09-17 22:14 UTC
if links with rel="stylesheet" have type="text/css" they are not imported automatically in safari and firefox. was working until 0.7.7. Possibly a regression.

Juergen

**Comment by Echogene** [comment] 2016-01-27 11:16
It seems like this has also been reported since in issue #460.  I am also experiencing this issue.

**Comment by paulie4** [comment] 2016-01-27 15:53
Sorry I missed this issue. I'm closing my other issue and moving my comment here:

The changes in https://github.com/webcomponents/webcomponentsjs/commit/c2d7ca1726112868c7d4105233815b8d28806e89 are causing ```<link rel="stylesheet" type="text/css" ...>``` tags, which are valid, to be ignored, but I think that change was just meant to ignore stylesheets with non-standard types, so can we add ```'link[rel=stylesheet][type="text/css"]'``` and ```'style[type="text/css"]'``` to the list of importsSelectors so they aren't ignored anymore?

**Comment by glamic-ep** [comment] 2016-04-20 16:40
It took me quite some time to figure out why my stylesheets were not loaded. I can confirm that the solution proposed by @paulie4 works. To speed things up I'm thinking of opening a PR.

**Comment by djm158** [comment] 2018-04-20 00:35
What's the status on this?

**Closed** 2019-06-07 18:52 UTC
