### ISSUE TITLE
template style change but will apply all

### ISSUE THREAD

**Issue by reehoiyan** [webcomponents/webcomponentsjs#626] opened 2016-09-24 10:16 UTC
Hi, 

I'm using other solution, but find out a problem.

I have two custom elements, when I dynamic change their colour, they have changed in their template style but they show the same colour in Firefox and Safari finally.

Left is chrome, right is Firefox (same as safari)

**Comment by reehoiyan** [comment] 2016-09-27 13:02
Hi,

I'm using other solution, but find out a problem.

I have two custom elements, when I dynamic change their colour, they have changed in their template style but they show the same colour in Firefox and Safari finally.

<img width="741" alt="screen shot 2016-09-27 at 8 53 51 pm" src="https://cloud.githubusercontent.com/assets/4879497/18874732/65736d8e-84f5-11e6-93f8-aa27ca12b155.png">

Left is chrome, right is Firefox (same as safari)

**Comment by notwaldorf** [comment] 2017-01-23 22:28
I'm going to close this since it doesn't have any repro steps, or screenshots, or details about how to reproduce this problem. What kind of css styles are you changing? Is it in a custom element, or a Polymer element? Please open a new issue with more details (preferably a JSBin with a reproducible example) if this is still happening :(

**Closed by notwaldorf** 2017-01-23 22:28 UTC
