### ISSUE TITLE
Specificity issue with slotted elements

### ISSUE THREAD

**Issue by mindthetic** [webcomponents/webcomponentsjs#898] opened 2018-02-21 21:33 UTC
In Firefox when I apply styles inside a custom element they are stronger than styles applied externally.

The below example

```html
<custom-element>
   <h1 class="green">Title</h1>
</div>
```
```css
.green {
    color: green;
}
```
custom-element.html
```css
:host .wrapper ::slotted(*) {
    color: red;
}
```

Will appear red in Firefox because when the polyfill runs it outputs

```css
custom-element .wrapper * {
    color: red;
}
```

which is more specific than
```css
.green {
    color: green;
}
```

Anyone experience this problem before?

**Comment by TimvdLippe** [comment] 2018-09-27 12:48
Closing this as a duplicate of https://github.com/webcomponents/shadycss/issues/206 Sadly we can not guarantee equivalent specificity after transforming the selectors. Maybe we can, in the linked issue, figure out a solution.

**Closed by TimvdLippe** 2018-09-27 12:48 UTC
