### ISSUE TITLE
<input> not accepting keyboard input disabled in Adobe CEP extension when using webcomponentjs

### ISSUE THREAD

**Issue by omarbelkhodja** [webcomponents/webcomponentsjs#1006] opened 2018-09-15 10:46 UTC
When using the following source code inside an Adobe CEP extension, typing with the keyboad inside the 2 first <input> elements doesn't write anything, whereas in the third one (create directly inside the body, and not using webcomponents) typing is OK. It seems that for some reason the keyboard input is blocked inside <input> inside webcomponents. Any idea why and how to debug it ?

```
<html>

<head>
    <script>
        // Force all polyfills on
        if (window.customElements) window.customElements.forcePolyfill = true;
        ShadyDOM = {
            force: true
        };
        ShadyCSS = {
            shimcssproperties: true
        };
    </script>
    <script src="node_modules/@webcomponents/webcomponentsjs/webcomponents-loader.js"></script>
</head>

<body>
    <template id="x-foo-from-template">
        <input value="from template">
    </template>
    <script>
        let tmpl = document.querySelector('#x-foo-from-template');

        customElements.define('x-foo-from-template', class extends HTMLElement {
            constructor() {
                super();
                let shadowRoot = this.attachShadow({
                    mode: 'open'
                });
                shadowRoot.appendChild(tmpl.content.cloneNode(true));
            }
        });

        customElements.define('x-foo-from-dynamic', class extends HTMLElement {
            constructor() {
                super();
                let shadowRoot = this.attachShadow({
                    mode: 'open'
                });
                var inputEl = document.createElement('input');
                inputEl.value = "from created element";
                shadowRoot.appendChild(inputEl);
            }
        });
    </script>

    <x-foo-from-template></x-foo-from-template>
    <x-foo-from-dynamic></x-foo-from-dynamic>
    <input value="in body">
</body>

</html>
```

**Comment by omarbelkhodja** [comment] 2018-09-15 11:05
When I monitor the events inside the document.body, I can see that when placing the cursor inside the <input> in body, and clicking on the keyboard, there are events TextInput, Input, KeyUp, Mouse event, etc... that are raised, whereas when performing the test inside the <input> inside the <x-foo-from-dynamic>, I can only see mouse events.

**Comment by TimvdLippe** [comment] 2018-09-27 11:26
> I'm forcing a shady dom. So the events should be available outside of the outer component.

ShadyDOM mimics shadow dom and thus makes sure that events that should not leave shadow dom don't leave the shadow dom. As @ptytb said, you need to listen to the direct element, which in this case is inside your shadow dom. Any event dispatched on an element in the shadow dom will normally not pierce through.

I am therefore closing this issue as working as intended. However, if you are still unsure how to proceed, feel free to comment! (Preferably with a JSBin I can debug to help you out)

**Closed by TimvdLippe** 2018-09-27 11:26 UTC

**Comment by TimvdLippe** [comment] 2018-09-27 12:35
@omarbelkhodja Thanks for the extra explanation! Sadly, we would need to see what the execution environment is doing to figure out whether this is an issue with the polyfill or an improper implementation in the environment. Would it be possible to show what the extension you are describing is doing? (Does https://github.com/Adobe-CEP/CEP-Resources host the source code of the extension?)
