### ISSUE TITLE
Babel 7 update required

### ISSUE THREAD

**Issue by AaronNGray** [webcomponents/webcomponentsjs#1012] opened 2018-09-20 17:12 UTC
$ npm install
npm WARN @babel/plugin-transform-classes@7.0.0-beta.35 requires a peer of @babel/core@7.0.0-beta.35 but none is installed. You must install peer dependencies yourself.

**Comment by TimvdLippe** [comment] 2018-09-27 11:19
Yes, we are waiting for a CLI release on this one. Closing this as duplicate of the above issue.

**Closed by TimvdLippe** 2018-09-27 11:19 UTC
