### ISSUE TITLE
webcomponentsjs throws an error in Safari, doesn't render elements

### ISSUE THREAD

**Issue by jannakha** [webcomponents/webcomponentsjs#164] opened 2015-01-23 01:45 UTC
webcomponents.js is broken in Safari: a simple demo of paper drop down menu doesn't render (polymer-project.org demos are using old version). Error doesn't say much, but looks like it's the new SVG shadow DOM stuff:

[Error] TypeError: Attempting to configurable attribute of unconfigurable property.
    defineProperty (webcomponents.min.js, line 11)
    j (webcomponents.min.js, line 11)
    H (webcomponents.min.js, line 11)
    (anonymous function) (webcomponents.min.js, line 12)
    global code (webcomponents.min.js, line 12)

**Comment by dmaslov** [comment] 2015-01-23 15:36
Agree with @jannakha 
Also doesn't work in iOS Safari and iOS Chrome.

**Comment by miztroh** [comment] 2015-01-23 16:00
Also reported here: https://github.com/Polymer/polymer/issues/1119

**Comment by addyosmani** [comment] 2015-01-23 16:10
To confirm, this is happening with 0.5.3. For now, please revert to using 0.5.2 until we've rolled a new release to address https://github.com/webcomponents/webcomponentsjs/pull/160 bring merged in.

**Comment by dmaslov** [comment] 2015-01-23 16:24
@addyosmani thanks for reply!

**Comment by azakus** [comment] 2015-01-23 18:51
Root cause: Safari has a broken descriptor for `ownerSVGElement`.
````javascript
{get: undefined, set: undefined, configurable: false, enumerable: true}
````

**Comment by jmesserly** [comment] 2015-01-23 18:53
yeah. see isBrokenSafari check in src/ShadowDOM/wrappers.js

**Comment by azakus** [comment] 2015-01-23 19:04
We still use the descriptor's `configurable` bit, which is `false` for this property.
Either we have to hack up some path in `registerObject` to have a blacklist, or manually make the wrapper :(

**Comment by azakus** [comment] 2015-01-23 22:06
Reverted #160 until we can fix it.

**Comment by arthurevans** [comment] 2015-01-24 01:33
If you're installing from Bower, you can now use 0.5.4, which is identical to 0.5.3 minus the problematic commit.

**Comment by davej** [comment] 2015-01-24 02:28
Thanks, working again. :+1:

**Closed** 2015-01-27 09:39 UTC

**Comment by ansorg** [comment] 2015-07-14 11:38
This seems to be again an issue in iOS 9 (Beta 3) on Safari iPhone, webapp using webcomponents version 0.5.5

    TypeError: Attempting to configurable attribute of unconfigurable property.
    definePropertywebcomponents.min.js:10:4150
    jwebcomponents.min.js:10:4150
    Hwebcomponents.min.js:10:4185
    (anonymous function)webcomponents.min.js:11:16300
    (anonymous function)webcomponents.min.js:11:16346

**Comment by ansorg** [comment] 2015-07-14 12:38
actually, I see the same error on iOS 9 and also in OS X Safari Version 9.0 (10601.1.37.1.2) when trying to load https://www.polymer-project.org/1.0/

**Comment by azakus** [comment] 2015-07-14 17:35
@ansorg This is most likely a new error given the Safari version bump. I'll track fixing it in #348
