### ISSUE TITLE
How to enable style scoping?

### ISSUE THREAD

**Issue by trusktr** [webcomponents/webcomponentsjs#1009] opened 2018-09-17 21:46 UTC
I tried the latest polyfill (2.1.3) in Firefox, but styles are clashing and broken. How do we turn on style scoping?

## Expected:

Chrome screenshot (good):

<img width="976" alt="screen shot 2018-09-17 at 2 44 15 pm" src="https://user-images.githubusercontent.com/297678/45652078-49b94f80-ba88-11e8-8832-4ac1d32822d1.png">

## Actual:

Firefox screenshot (clashing styles from other SVGs in the site):

<img width="977" alt="screen shot 2018-09-17 at 2 44 55 pm" src="https://user-images.githubusercontent.com/297678/45652100-5dfd4c80-ba88-11e8-8134-103b808ce493.png">

**Comment by trusktr** [comment] 2018-09-17 21:47
The reason I'm using ShadowDOM is because I'm placing generated SVG code (which includes styles) into Shadow Roots so that generated class names don't clash.

This is easier than editing the SVGs and changing all the class names. I'm just taking Designers' output and sticking them in the shadow roots for encapsulation, and it works great in Chrome.

**Comment by trusktr** [comment] 2018-09-17 21:52
Looks like https://github.com/webcomponents/webcomponentsjs/issues/422 is the answer, I will try it...

However I think style scoping should be default. Why isn't it default?

**Comment by trusktr** [comment] 2018-09-17 21:58
I'm reading the README at https://github.com/webcomponents/shadycss but I'm not sure what to do.

I'm not making custom elements, I'm only making a shadow root on a regular `div` element then sticking the SVG and its style inside.

What should I do to make it work?

**Comment by TimvdLippe** [comment] 2018-09-17 22:31
You dont need to use custom elements if you only need styling. Create a template with your styles, call shadycss, append the template to your shadow root. Make sure you are also loading shadow dom for that.

**Comment by trusktr** [comment] 2018-09-18 01:48
I can't seem to get it to work, I still have clashing styles in FireFox. My code is like this:

```js
for (const i in graphics) {
    const tmpl = document.querySelector('template#number-' + i)
    const div = document.createElement('div')

    window.ShadyCSS &&
      ShadyCSS.prepareTemplate(tmpl, 'div');

    window.ShadyCSS &&
      ShadyCSS.styleElement(div);

    const root = div.attachShadow({mode: 'open'})
    root.appendChild(
      document.importNode(tmpl.content, true)
    )

    // ... append the `div` somewhere in the page ...
}
```

The styles from the shadow roots are still conflicting with each other.

Is it because they all have the same `"div"` namespace?

**Comment by trusktr** [comment] 2018-09-18 01:52
I changed 

```js
    window.ShadyCSS &&
      ShadyCSS.prepareTemplate(tmpl, 'div');
```

to

```js
    window.ShadyCSS &&
      ShadyCSS.prepareTemplate(tmpl, 'div-' + Math.random());
```

and that yields different results, but the styles are still garbled up.

Chrome:

<img width="1162" alt="screen shot 2018-09-17 at 6 52 01 pm" src="https://user-images.githubusercontent.com/297678/45659756-d07f2400-baaa-11e8-8561-c67998ef31dd.png">

Firefox:

<img width="1229" alt="screen shot 2018-09-17 at 6 52 12 pm" src="https://user-images.githubusercontent.com/297678/45659761-d412ab00-baaa-11e8-83a5-155cf2e376db.png">

**Comment by trusktr** [comment] 2018-09-18 02:05
Alright, I got it almost fully working. I changed my code to this:

```js
let counter = 'a'

for (const i in graphics) {
    const tmpl = document.querySelector('template#number-' + i)
    const div = document.createElement('div')

    window.ShadyCSS &&
      ShadyCSS.prepareTemplate(tmpl, counter+='a');

    window.ShadyCSS &&
      ShadyCSS.styleElement(div);

    const root = div.attachShadow({mode: 'open'})
    root.appendChild(
      document.importNode(tmpl.content, true)
    )

    // ... append the `div` somewhere in the page ...
}
```

so it make the string `"aa"`, `"aaa"`, and so on, which mostly works, but there's still some small differences in the graphics:

Expected (Chrome):

<img width="1216" alt="screen shot 2018-09-17 at 7 04 21 pm" src="https://user-images.githubusercontent.com/297678/45660222-89922e00-baac-11e8-94e1-4b0effe4142d.png">


Almost but not quite (FireFox):

<img width="1175" alt="screen shot 2018-09-17 at 7 04 31 pm" src="https://user-images.githubusercontent.com/297678/45660231-96af1d00-baac-11e8-9d58-425561b1556b.png">

**Comment by TimvdLippe** [comment] 2018-09-18 11:06
@trusktr Great you got that figured out :tada: I think ShadyCSS should. Since you made an issue already (awesome, thanks!), I am closing this as duplicate of https://github.com/webcomponents/shadycss/issues/208 Hopefully we can get to that issue soon :smile:

**Closed by TimvdLippe** 2018-09-18 11:06 UTC

**Comment by trusktr** [comment] 2018-09-18 16:46
@TimvdLippe For now the following makes everything look good (removing the original styles after calling ShadyCSS APIs):

```js
import * as bases from 'bases'
let counter = 1

for (const i in graphics) {
    const tmpl = document.querySelector('template#graphic-' + i)
    const div = document.createElement('div')

    window.ShadyCSS &&
      ShadyCSS.prepareTemplate(tmpl, 'ScopedStyleName_'+bases.toBase52(counter++));

    window.ShadyCSS &&
      ShadyCSS.styleElement(div);

    const root = div.attachShadow({mode: 'open'})
    root.appendChild(
      document.importNode(tmpl.content, true)
    )

    // ... append the `div` somewhere in the page ...
}

// remove all original styles (the generated ones are in the <head>)
for (const style of Array.from(document.body.querySelectorAll('style'))) {
  style.remove()
}
```
