### ISSUE TITLE
Combining :host-context and :host selector doesn't work when polyfilled

### ISSUE THREAD

**Issue by stevehansen** [webcomponents/webcomponentsjs#146] opened 2015-01-06 13:19 UTC
Using the following style works on Chrome but the generated polyfill css is invalid.

```
<style>
  :host-context(.blocky):host(:hover) {
    display: block;
    background: red;
  }
</style>
```

The following css is produced (on Internet Explorer but it also doesn't work on Firefox):

```
<style shim-shadowdom-css="">
  x-foo.blockyx-foo -no-combinator:hover, .blocky x-foox-foo -no-combinator:hover {
     background: red; display: block;
  }
</style>
```

A complete sample can be found at http://jsbin.com/fozolecitu/1/edit?html,output

**Comment by addyosmani** [comment] 2015-01-08 19:31
Confirmed that the original sample does not work in Firefox, but `:host-context(.blocky):hover ` works absolutely fine http://jsbin.com/fiqedovabu/2/edit in target browsers. 

I wasn't aware `:host-context(.blocky):host(...)` was supported. @jmesserly do you have any insights here?

**Comment by Sleeckx** [comment] 2015-01-08 21:20
Using only `:host-context(.blocky):hover` doesn't seem to work in Chrome.

**Comment by jmesserly** [comment] 2015-01-08 21:59
@sorvell would be more familiar with the ShadowCSS shim ... but `:host-context(.blocky):hover` looks the most reasonable to me. Based on my reading of the spec at http://dev.w3.org/csswg/css-scoping/#host-selector I think that should be equivalent to `:host-context(.blocky):host(:hover)` ... but it doesn't look like the code supports that.

**Comment by JosefJezek** [comment] 2016-09-12 15:32
Please resolve this issue...

I need this combination
```css
:host-context(.page[active][loaded]):host([animated]) {
  animation: fadeIn cubic-bezier(0.4, 0, 0.2, 1) 1s;
}
```

Chrome is OK, but Firefox not :-( This code is working on Firefox, but not on Chrome...

```css
:host-context(.page[active][loaded])[animated] {
  animation: fadeIn cubic-bezier(0.4, 0, 0.2, 1) 1s;
}
```

**Comment by wazzzap** [comment] 2016-09-16 09:20
:host-context(.class):host(:first-item) - works only in chrome
:host-context(.class):first-item - works in all other browsers - this seems to be a polyfill problem?

**Comment by tonysamperi** [comment] 2018-03-09 15:40
Need this too..

    :host-context(.mat-form-field-type-ubi-mat-time-input.mat-form-field-can-float)` {
        ::ng-deep span > label.mat-input-placeholder {
            opacity: 0;
         }
    }

Doesn't seem to work neither...also tried /deep/ but same result

**Comment by TimvdLippe** [comment] 2018-06-17 16:11
This is a duplicate of https://github.com/webcomponents/shadycss/issues/74

**Closed by TimvdLippe** 2018-06-17 16:11 UTC
Labels: question
