### ISSUE TITLE
Object doesn't support property or method 'call' on IE11

### ISSUE THREAD

**Issue by 19jake68** [webcomponents/webcomponentsjs#830] opened 2017-08-18 18:53 UTC
Description:
I update my webcomponentjs from `v1.0.7` to `v1.0.8` then after trying to run my polymer app, I encountered the error on the screenshot below.

My app works well on IE11 with webcomponentjs 1.0.7, and I encountered this yesterday after updating to 1.0.8.

Screenshot:
![image](https://user-images.githubusercontent.com/8743844/29473194-72e664d2-8489-11e7-8faa-4567b4c0f807.png)

**Comment by gigmania** [comment] 2017-09-07 19:28
Did you find a fix for this? I am getting the same error.

**Comment by jab** [comment] 2017-09-12 20:23
FWIW I recently deployed a fresh PSK2 site to https://uproxy.github.io/uproxy.org/, ended up with webcomponentsjs v1.0.10 (latest release at time of writing), and am getting a similar error (`SCRIPT438: Object doesn't support property or method 'values'`):

![screen shot 2017-09-12 at 16 19 18](https://user-images.githubusercontent.com/64992/30346402-8f0fa7da-97d6-11e7-8d09-53828e8f5a0f.png)

**Comment by snuggs** [comment] 2017-09-13 09:15
FWIW We have been getting the same error as well and didn't realize it until doing some Browserstack testing recently. /cc @brandondees @robcole

**Comment by azakus** [comment] 2017-09-13 19:55
I think I need a bit more information here. Did you deploy with `polymer build`, and if so, at what version?

**Comment by notwaldorf** [comment] 2017-09-13 20:05
@azakus we're seeing it on tests too, if it helps
- https://travis-ci.org/PolymerElements/iron-form/builds/252597504
- https://travis-ci.org/PolymerElements/app-localize-behavior/builds/275151585

**Comment by azakus** [comment] 2017-09-13 21:05
Thanks. I couldn't get this to reproduce with a simple element, so it must be related to some element or elements use of an API.

**Comment by jab** [comment] 2017-09-13 22:17
Are these related?
- https://github.com/webcomponents/custom-elements/issues/103
- https://github.com/webcomponents/custom-elements/pull/57

**Comment by ernsheong** [comment] 2017-11-06 11:14
I'm seeing this in Edge 15
![image](https://user-images.githubusercontent.com/1343284/32438632-32267852-c326-11e7-82f9-a5536266f4c8.png)

But oddly it only happens in development environment... 🤷‍♂️ And it proceeds to load a whole bunch of development dependency stuff:

![image](https://user-images.githubusercontent.com/1343284/32438736-914279c6-c326-11e7-911e-007a34768462.png)

Oddly staging/production build is fine, but I have no idea what made the difference.

**Comment by azakus** [comment] 2017-12-14 20:21
It looks like this can happen when the developer tools are open in IE, as it adds some sort of `FunctionWrapper` object as an event listener, which is neither `call`able nor has a `handleEvent` object.

The check in event handling assumes that if an object doesn't have a `handleEvent` method that is is a callable function.

**Comment by cwenzelg** [comment] 2017-12-14 20:47
We experience the same Problem with Version 1.0.20. The Page also is not loading even with a closed developer tool. We also get additional 2 Syntax Errors for webcomponents-lite.js. Sometimes the IE 11 Crashed because the script keeps running. Firefix, Edge, Chrome all work fine.
IE Version is: 11.98.16299.0

**Comment by azakus** [comment] 2017-12-14 22:04
@cwenzelg that sounds like perhaps a different issue if you're seeing syntax errors.

**Closed** 2017-12-15 19:40 UTC
Labels: bug, ie

**Comment by cwenzelg** [comment] 2017-12-19 16:35
The fix worked, the new Version 1.0.21 fixed that issue for me. (well not the Syntax Error) but the call error. thank you
