### ISSUE TITLE
Stamped template from import doc or main page do not execute their script when constructed with innerHTML

### ISSUE THREAD

**Issue by tomalec** [webcomponents/webcomponentsjs#470] opened 2015-12-23 16:08 UTC
It seems that with polyfilled HTML Imports and/or Template, 
`<script>`s from `<template>` tag loaded from imported document, does not execute when stamped to document (in fact they do not execute at all)

document to import: 

``` html
<template>
    ...
    <script>
        console.log('template\'s script executed');
    </script>
</template>
```

then after 

``` js
var template = document.getElementById('myImport').import.querySelector('template');
var clone = document.importNode(template.content, true);
document.body.appendChild(clone);
```

nothing happens. With native support - Chrome - it works fine.

Here is a live example: http://plnkr.co/edit/wECddsw3mZBudK6rlL5n?p=preview

**Comment by tomalec** [comment] 2015-12-28 10:59
I have reduced the issue, and removed HTML Imports out of question:
http://jsbin.com/jacubi/edit?html,output
```js
var container = document.createElement('div');
container.innerHTML = "<template>Script stamped. Have you seen alert msg? <" +
    "script>alert('works');console.log('template`s script executed');" +
    "</" +
    "script></template>";
var template = container.querySelector('template');
// Decorate tempalte as HTML Imports polyfill does
if (window.HTMLTemplateElement && HTMLTemplateElement.bootstrap) {
    HTMLTemplateElement.decorate(template);
}


var clone = document.importNode(template.content, true);
document.body.appendChild(clone);
```

Simply, `<script>` tags from stamped `<template>` are not executed.

**Comment by tomalec** [comment] 2015-12-28 15:44
I have figured out a workaround http://jsbin.com/jiwidu/edit?html,output
```js
// Workaround https://github.com/webcomponents/webcomponentsjs/issues/470
if(HTMLImports && !HTMLImports.useNative && HTMLImports.parser){
    var nodes = clone.querySelectorAll(HTMLImports.parser.importsSelectors);
    for (var nodeNo=0, l=nodes.length, node; (nodeNo<l) && (node=nodes[nodeNo]); nodeNo++) {
        HTMLImports.parser.parseDynamic(node, true);
    }
}
// Stamp tempalte into root document
document.body.appendChild(clone);
// Last bit of workaround
if(HTMLImports && !HTMLImports.useNative && HTMLImports.parser){
    HTMLImports.parser.parseNext();
}
```
But it's quite heavy, and this time it make HTMLTemplate polyfill require HTML Imports polyfill.
Needless to say that this workaround depends heavily on undocumented polyfill internals.

**Comment by ebidel** [comment] 2015-12-28 16:58
We ran into this when developing the I/O 2015 web app. There were a couple of issues:

- IE didn't have `<template>` at the time, so we had to create a [workaround](https://github.com/GoogleChrome/ioweb2015/blob/master/app/templates/home.html#L266) that delayed executing the imported `<template>`'s `<script>` until other scripts had run
- FF (which has `<template>`) does not execute script within an imported template. Our [workaround](https://github.com/GoogleChrome/ioweb2015/blob/master/app/scripts/helper/router.js#L160-L173) was to pull the scripts from the template and run then.

In https://github.com/webcomponents/webcomponentsjs/issues/470#issuecomment-167542450, you're using `.innerHTML` to set the template content. From the HTML spec:

> script elements inserted using innerHTML do not execute when they are inserted.

As an example, [this](http://jsbin.com/cesireb/edit?html,output) **doesn't run in Chrome**:

```html
<script>
  var name = "<script>alert('I am John in an annoying alert!')<\/script>";
  document.body.innerHTML = name;
</script>
```

If you instead [use declarative markup directly](http://jsbin.com/hosaca/edit?html,output), **the alert shows**:

```html
  <template>
    Script stamped. Have you seen alert msg?
    <script>
      alert('works');
      console.log('template\'s script executed');
    </script>
  </template>
  <script>
    var template = document.querySelector('template');
    var clone = document.importNode(template.content, true);
    document.body.appendChild(clone);
  </script>
```

So, Chrome executes `<script>` in a template when it's set with `.innerHTML`. FF and Safari do not.
The reason this manifests itself when using polyfills may be [here](https://github.com/webcomponents/webcomponentsjs/blob/master/src/HTMLImports/importer.js#L146), where the HTML imports polyfill uses `.innerHTML`.

I filed crbug.com/572693 to see what the intended behavior is. Regardless, it's not good Chrome is different than FF/Safari. Wasn't able to test in Edge.

**Comment by tomalec** [comment] 2015-12-28 17:25
Thanks @ebidel for elaborate answer :)

I have noticed that `.innerHTML` is a problem, that's why I squezed workaround out of HTML Imports polyfill.

However, my original issue, was about templates from imported documents.
So, the ones, that does not fall into 
> script elements inserted using innerHTML do not execute when they are inserted.
and if I understood spec correctly should work.

Therefore, `.innerHTML` is just buggy implementation detail. 
Maybe we could go back to the title: "scripts stamped from imported document's template are not executed" ;) Then either
1. Somehow, do not use `innerHTML` in HTML Imports shim, as according to spec it should fail, or,
2. Execute `.parser`  for stamped imported templates, as well as any other imported content.

**Comment by ebidel** [comment] 2015-12-29 04:15
@azakus @garlicnation should have a look at this.

**Comment by tomalec** [comment] 2016-01-04 17:18
It seems, original issue is not (only) caused by `.innerHTML` in HTML Imports polyfill
Even if I add `<script>` tag using `template.content.appendChild(script);` it still does not execute it
```js
        var template = document.getElementById('myImport').import.querySelector('template');
        var script = document.createElement('script');
        script.text = 'alert("template\'s script executed")';
        template.content.appendChild(script);
        var clone = document.importNode(template.content, true);
        document.body.appendChild(clone);
```
http://plnkr.co/edit/lmZkx95FOj2pbiOCBEXv?p=preview

**Comment by azakus** [comment] 2016-01-05 00:42
You should use `script.textContent = 'alert("template\'s script executed")';`

**Comment by tomalec** [comment] 2016-01-05 00:49
Thanks, but it still does not make it work in IE (at least for me)

**Comment by azakus** [comment] 2016-01-05 00:51
Not surprised it doesn't work in IE, the template polyfill doesn't handle `document.importNode`.

**Comment by azakus** [comment] 2016-01-05 01:09
Looks like FF at least treats any script created with `innerHTML` as tainted:
```js
var div = document.createElement('div');
div.innerHTML = '<template><script>console.log("NEW")</scr' + 'ipt></template>';
document.body.appendChild(div);
var frag2 = document.importNode(div.firstElementChild.content, true);
document.body.appendChild(frag2);
```

This runs in Chrome, but not FF, Safari, or IE.

**Comment by tomalec** [comment] 2016-01-05 19:28
As Eric [mentioned](https://github.com/webcomponents/webcomponentsjs/issues/470#issuecomment-167603329) it's so according to [spec](http://www.w3.org/TR/html5/scripting-1.html)
>when inserted using innerHTML and outerHTML attributes, they do not execute at all.

**Comment by tomalec** [comment] 2016-11-17 12:49
Unfortunately, it seems that my workaround has side effects, as it may result in calling `load` event on `<link rel="import">` that results in 404 - should trigger `onerror`. Does somebody have better idea?

**Comment by TimvdLippe** [comment] 2018-09-17 16:53
Since we no longer have HTML Imports in v2, I am closing this issue.

**Closed by TimvdLippe** 2018-09-17 16:53 UTC
Labels: v0
