### ISSUE TITLE
Argument 1 of MutationObserver.observe does not implement interface Node, on shadow root

### ISSUE THREAD

**Issue by trusktr** [webcomponents/webcomponentsjs#935] opened 2018-05-10 18:35 UTC
My custom elements work great in Chrome. Of course, FireFox doesn't have CE yet so I tried to add this polyfill.

My custom elements use MutationObserver, and now that I try my elements in FF with this polyfill, I see an error like

```
TypeError: Argument 1 of MutationObserver.observe does not implement interface Node.
```

My Custom Element has a method `attachShadow` that is somewhat like follows (cut really short for brevity):

```js
class MyEl extends HTMLElement {

    // ...

    attachShadow( options ) {
        const root = super['attachShadow']( options )

        const observer = new MutationObserver(changes => {
            // ... do stuff with changes ...
        })

        observer.observe( root, { childList: true } ) // <---------------- TypeError

        return root
    }

    // ...

}
```

After adding the sd-ce polyfill and trying in Firefox, the `observer.observe` line is what triggers the error.

How can we fix this? With the v0 polyfill, there was something like `wrap`/`unwrap`. Do we need something like this for the v1 polyfill?

**Comment by trusktr** [comment] 2018-05-10 19:01
Note, my example is simplified, and my custom elements class does `return Reflect.construct(HTMLElement, [], new.target)`, so all that is fine.

**Comment by TimvdLippe** [comment] 2018-05-10 19:50
Duplicate of https://github.com/webcomponents/shadydom/issues/234

**Closed by TimvdLippe** 2018-05-10 19:50 UTC
