### ISSUE TITLE
'wrap' function in webcomponents-lite.js, conflicts with j-query generated object having 'wrap' id.

### ISSUE THREAD

**Issue by rathor-ashwin** [webcomponents/webcomponentsjs#490] opened 2016-02-10 05:30 UTC
a function 'wrap' used in webcomponents-lite.js, conflicting with an object id 'wrap' which is jquery generated, in a web page.this issue is there in firefox and ie but works proper in chrome.

**Comment by notwaldorf** [comment] 2017-01-23 23:41
Duplicate of https://github.com/webcomponents/webcomponentsjs/issues/529

**Closed by notwaldorf** 2017-01-23 23:41 UTC
