### ISSUE TITLE
WebGLRenderingContext not properly wrapped?

### ISSUE THREAD

**Issue by pixels4nickels** [webcomponents/webcomponentsjs#432] opened 2015-10-30 19:13 UTC
When using THREE.js in Safari 9 on a page implementing webcomponentsjs, the context is missing the getExtension function and fails to properly initialize.

TypeError: a.getExtension is not a function. (In 'a.getExtension(c)', 'a.getExtension' is undefined)
getthree.min.js:580:183

Where "a" is a WebGLRenderingContext.
My workaround for this was to use the webcomponents-lite.js for now.

**Comment by markhats** [comment] 2015-11-25 15:47
Duplicate of https://github.com/webcomponents/webcomponentsjs/issues/414 I think. Any chance of a fix?

**Comment by pixels4nickels** [comment] 2015-11-25 17:20
I will try and look at it more this week

**Comment by TimvdLippe** [comment] 2018-04-14 18:24
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!

**Closed by TimvdLippe** 2018-04-14 18:24 UTC
