### ISSUE TITLE
IE throws error

### ISSUE THREAD

**Issue by tigerhawkvok** [webcomponents/webcomponentsjs#184] opened 2015-02-01 01:55 UTC
IE throws the following error:

```
SCRIPT438: Object doesn't support property or method 'getAttribute'
File: webcomponents.js, Line: 956, Column: 9
```

In my specific use case, it's triggering off this [Bootstrap](http://getbootstrap.com/javascript/#collapse)/Polymer blend:

``` html
<paper-button data-toggle="collapse" data-target="#collapse-advanced" aria-expanded="false" aria-controls="collapse-advanced" class="materialbluegrey" id="collapse-button" raised>Advanced Options <core-icon icon="unfold-more" id="collapse-icon"></core-icon></paper-button>
```

**Comment by addyosmani** [comment] 2015-02-02 11:18
Is it possible to provide us with a reduced test case that repros this issue? Unfortunately, it's hard for us to debug the blend of libraries you're using to determine if a fix is needed.

**Comment by silentHoo** [comment] 2015-02-03 15:34
+1 here. I'm using the current #master. I'm just running this webcomponent testsuite: https://silenthoo.github.io/webcomponents-performance-test/test-polyfilled.html and it seems to crash right after `DOMContentLoaded` is fired.

**Comment by garlicnation** [comment] 2015-02-03 19:14
@addyosmani This seems potentially related to #72. In which case it could have existed for some time.

**Comment by garlicnation** [comment] 2015-02-03 19:17
It looks like #185 may have resolved this issue?

**Comment by silentHoo** [comment] 2015-02-03 21:18
Hm okay, I tested it against 0.5.3, 0.5.2 and 0.5.1. Everytime the same issue.  I'll try to locate a bug in my source code. I'll give you some feedback if I've found out more.

**Comment by brendanbradford** [comment] 2015-02-06 02:31
this seems to be a failing in the 'import' command....:
eg if the script below in the main page, the import fails... (same error is produced).
also, the import doesnt load scripts from an IMPORT page... (eg. the common suggestion of using an import page to load jquery).

the *first* time the link is added, any script in the imported HTML is run (eg. if you have code to load a content div from the import file). but subsequently doing a getElement and removing the link, then adding it will not run the script in the file...

       var impLink = document.createElement('link');
        impLink.rel = 'import';
        impLink.href = hash + '.html';
        impLink.id = hash + '_html';
        impLink.onload = function (e) {
            var impId = this.id;
            impId =  '#' + impId.replace('_html','_page');
            var content = this.import.querySelector(impId);
            var wrapper = document.getElementById('page-wrapper');
            var clone = content.cloneNode(true);
            wrapper.innerHTML = '';
            wrapper.appendChild(clone); 
        };   
        impLink.onerror = function(e) {
            alert('error loading ' + e);
        };     
        document.body.appendChild(impLink);

**Comment by tigerhawkvok** [comment] 2015-02-07 00:07
Here's a reduced test case that replicates it (sorry for the delay!)

https://tigerhawkvok.github.io/webcomponentsjs-issue-184-test/index.html

via

https://github.com/tigerhawkvok/webcomponentsjs-issue-184-test

**Comment by addyosmani** [comment] 2015-02-07 20:28
Thanks for the reduced test case @tigerhawkvok. Will re-check this next week.

**Comment by chrisackatcaci** [comment] 2015-02-20 14:14
This prevents us from using Polymer in our project so I'm monitoring this issue carefully. Any progress so far?

**Comment by garlicnation** [comment] 2015-02-20 21:44
There seems to be a change in how IE loads scripts in ie11. see the unrelated: http://blog.getify.com/ie11-please-bring-real-script-preloading-back/

@tigerhawkvok Thanks so much for the reduced case! I've discovered:

- There's no bug in ie10.
- In ie11, if all the scripts are local, this doesn't occur.

**Comment by chrisackatcaci** [comment] 2015-02-22 01:16
@garlicnation Do you know if there is a way to make this work. I'm not sure what it means for the scripts to be local but is there any way to make this work? Thanks!

**Comment by garlicnation** [comment] 2015-02-24 19:59
@chrisackatcaci I'm looking into this more. I hope to have a PR out soon that resolves this. I have a version that works but causes massive startup slowdowns in IE.

**Comment by nebojsa-simic** [comment] 2015-04-23 10:42
so practicaly polymer is unusable in ie11 ?

**Comment by brandonbuttars** [comment] 2015-05-18 14:36
Any progress with this?

**Comment by N4M3Z** [comment] 2015-09-07 20:28
It might be worth noting that this issue has disappeared for me once I started loading [webcomponents](https://github.com/WebComponents/webcomponentsjs) using [RequireJS](http://requirejs.org):
```
require(["webcomponents"], function () { ... });
```

**Comment by kajackdfw** [comment] 2015-10-08 14:04
I am seeing this same issue in my project for IE 11 running in Edge mode. Only one of my components ( larapoly_double_select )  provokes the issue 184 when the ready function runs.  My demo project is a stand alone demo page complete with components, so it should be easy for anyone to see the webcomponents issue. 

https://github.com/kajackdfw/eeu_components

**Comment by kajackdfw** [comment] 2015-10-08 14:23
My project has in common with the previous issue descriptions : 
1 ) Bootstrap / Polymer blend with a toggle drop-down call.

**Comment by addyosmani** [comment] 2015-10-08 14:31
@garlicnation do you remember if we landed a patch based on your work back in Feb off the back of this?

**Comment by kajackdfw** [comment] 2015-10-08 15:16
My project is only one month old, so I am using all the newest releases. My webcomponents file is dated  ( Build Time: 2015-09-28T16:50:31-0700 ) , pulled from the Bower repo.

**Comment by kajackdfw** [comment] 2015-10-09 14:20
My IE / webcomponents issue went away today. I refactored some of my code inside a jquery each structure, and the issue went away. I need no additional help. If you want to examine the change fix for my bootstrap/wc conflict, my fix was here.

https://github.com/kajackdfw/eeu_components/commit/b84c4b10a7f56592fafc904d8a282f52f561a649

see previous versions for the IE/Bootstrap/wc issue.

Thanks and keep up the great work. I really love the Polymer project.

**Comment by garlicnation** [comment] 2015-10-09 18:01
@addyosmani From what I remember, this bug spontaneously disappeared after an IE update. I don't believe I ever merged anything for it.

**Comment by kajackdfw** [comment] 2015-10-09 19:00
Yes, i believe you are correct. I changed my component code to avoid the error condition. The lesson i learned was  
:-1 Do not use this.myPolimerVar inside the Jquery $.each structure
:+1 Use local vars inside the $.each only.
:+1 Each-ing thru a Polymer Property Arrays is ok, 
:8ball:  JQuery $.each has its own scope and can alter polymer properties inside the structure.

Since my set of components are intended for a Bootstap / JQuery / Laravel environment, JQuery is acceptable inside my components, but for NONE Laravel projects, JQuery will be forbidden inside my web components.

**Comment by TimvdLippe** [comment] 2018-04-03 21:48
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!

**Closed by TimvdLippe** 2018-04-03 21:48 UTC
Labels: question
