### ISSUE TITLE
Webcomponents not working with Vue web-components-wrapper 1.2 and IE11

### ISSUE THREAD

**Issue by BryanKuiper** [webcomponents/webcomponentsjs#1048] opened 2018-11-02 09:45 UTC
The webcomponent I have created with The latest vue-cli and @vue/web-components-wrapper does not seem to work in IE11. 
I have set up a minimalistic test case: https://github.com/BryanKuiper/webcomponents-in-ie11

What I expect to see (works in Firefox ^61, Chrome, Safari and Edge):

![image](https://user-images.githubusercontent.com/30691301/47906897-784d8700-de8a-11e8-91ef-9d8e8a0858ea.png)

What I actually see in IE11:

![image](https://user-images.githubusercontent.com/30691301/47907015-b8ad0500-de8a-11e8-99d1-1560f27c00ae.png)

The console mentions the following:

![image](https://user-images.githubusercontent.com/30691301/47907596-dcbd1600-de8b-11e8-91bf-598ae2b8d47d.png)

The first line mentions "Insufficient stack space" in webcomponents-bundle.js (78, 291)
The second line mentions "Stackoverflow op line 78"
The third line mentions an unexpected </body>-tag

I think the third line is caused by the first and second errors but I cannot figure out how to solve those errors. Can somebody please tell me if I am missing something?

**Comment by web-padawan** [comment] 2018-11-02 09:49
You can find the working example here: https://github.com/vaadin/base-starter-vue/tree/p3-preview

**Comment by web-padawan** [comment] 2018-11-02 11:29
To be clear, our demo project is about using third party Web Components in Vue projects, but not about using Web Components as a compile target for Vue CLI. So no, we haven't tried that.

**Comment by jhuesos** [comment] 2018-12-13 16:20
This is probably related to this issue: https://github.com/webcomponents/webcomponentsjs/issues/1042

You can't use `@babel/polyfills` with WebComponents polyfills. Vue, by default, configures `@babel/preset-env` to set `useBuiltIns: 'usage'` so it will load babel polyfills and they will somehow conflicts with WebComponents polyfills.

This has been an open issue for a while, I guess this is not a more popular issues.

Related issues (I think):

https://github.com/webcomponents/webcomponentsjs/issues/891
https://github.com/webcomponents/webcomponentsjs/issues/993
https://github.com/webcomponents/webcomponentsjs/issues/972
...

I think the important thing is to get this change done:

https://github.com/webcomponents/webcomponentsjs/issues/1007

To expose bare-minimum polyfills, so they can be merged and integrated with Babel Polyfills. Vote up to give it more priority :)

**Comment by TimvdLippe** [comment] 2019-01-09 16:12
I am closing this as duplicate of the other issues.

**Closed by TimvdLippe** 2019-01-09 16:12 UTC
