### ISSUE TITLE
extending native elements: SVG

### ISSUE THREAD

**Issue by azakus** [webcomponents/webcomponentsjs#524] opened 2016-04-15 23:23 UTC
_From @bradjohnwoods on March 5, 2016 0:47_

Currently you can't extend SVG elements, I was told this was because of a namespace issue?
- Polymer: v1.2.0
- webcomponents: v0.7.21 

_Copied from original issue: Polymer/polymer#3495_

**Comment by azakus** [comment] 2016-04-15 23:25
FWIW, this is mostly due to the feeling that extending SVG elements will be used too little to justify the engineering effort. We're open to hearing your use-case though.

**Comment by chrisprice** [comment] 2016-10-19 12:07
A friendly use-case ping for @azakus :smiley:

**Comment by TimvdLippe** [comment] 2018-07-03 10:53
Closing this as duplicate of https://github.com/webcomponents/custom-elements/issues/13

**Closed by TimvdLippe** 2018-07-03 10:53 UTC
Labels: enhancement, v0
