### ISSUE TITLE
TypeError: Unable to get property 'call' of undefined or null reference 

### ISSUE THREAD

**Issue by firstor** [webcomponents/webcomponentsjs#824] opened 2017-08-09 09:24 UTC
I got this error message in `webcomponents-hi-sd-ce.js` and `webcomponentjs-lite.js`, that is, on IE and Edge. The error happened on the production build (built with `polymer build`).

#### Reproduction
https://github.com/first87/polymer-server/tree/8c2bbd98a52e3280b0d2a27b46fb38fda38daab6

#### The error can be resolved with `webcomponentsjs 1.0.1`.
https://github.com/first87/polymer-server/commit/c240575af45ab4fb78fc848230473ac93ae71787

Hope to solve this error with new release.

**Comment by feuerste** [comment] 2017-08-10 07:03
Duplicate of #822?

**Comment by first87** [comment] 2017-08-16 06:58
@feuerste The error itself seems duplicate, however I couldn't resolve the error with v1.0.7.

**Comment by satvik1986** [comment] 2018-04-18 07:05
DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
login
HTML1300: Navigation occurred.
login
Angular is running in the development mode. Call enableProdMode() to enable the production mode.
[object Object]
   {
      [functions]: ,
      __proto__: { },
      authToken: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJnaXZlbl9uYW1lIjoiMTU4IiwianRpIjoiNmJlZWI1OTQtZDY1My00NzVkLTg4ZTgtNDViMDhhMmI1Nzc2IiwibmJmIjoxNTI0MDM0MzkwLCJleHAiOjE1MjkyMTgzOTAsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTkwNTcvIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1OTA1Ny8ifQ.ck3SZPfAF-mFusYOk5x8NJ8hF3XsHqbFpcOROXmyhLs",
      email: "padmin",
      firstName: "site",
      fullname: "site s",
      imageUrl: "2.jpg",
      lastName: "s",
      Symbol()_g.7t813rgg29b: undefined,
      Symbol(observable)_i.7t813rgg29b: undefined,
      Symbol(rxSubscriber)_h.7t813rgg29b: undefined,
      userID: 158
   }

Error: Uncaught (in promise): TypeError: Unable to get property 'call' of undefined or null reference
TypeError: Unable to get property 'call' of undefined or null reference
   at __webpack_require__ (http://localhost:4200/inline.bundle.js:55:12)
   at eval code (eval code:15:1)
   at ../../../../../src/app/admin-layout/change-password/change-password.component.ts (http://localhost:4200/admin-layout.module.chunk.js:59:1)
   at __webpack_require__ (http://localhost:4200/inline.bundle.js:55:12)
   at eval code (eval code:6:1)
   at ../../../../../src/app/admin-layout/admin-layout.routing.ts (http://localhost:4200/admin-layout.module.chunk.js:15:1)
   at __webpack_require__ (http://localhost:4200/inline.bundle.js:55:12)
   at eval code (eval code:15:1)
   at ../../../../../src/app/admin-layout/admin-layout.module.ts (http://localhost:4200/admin-layout.module.chunk.js:7:1)
   at __webpack_require__ (http://localhost:4200/inline.bundle.js:55:12)
   {
      [functions]: ,
      __proto__: { },
      description: "Uncaught (in promise): TypeError: Unable to get property 'call' of undefined or null reference
TypeError: Unable to get property 'call' of undefined or null reference
   at __webpack_require__ (http://localhost:4200/inline.bundle.js:55:12)
   at eval code (eval code:15:1)
   at ../../../../../src/app/admin-layout/change-password/change-password.component.ts (http://localhost:4200/admin-layout.module.chunk.js:59:1)
   at __webpack_require__ (http://localhost:4200/inline.bundle.js:55:12)
   at eval code (eval code:6:1)
   at ../../../../../src/app/admin-layout/admin-layout.routing.ts (http://localhost:4200/admin-layout.module.chunk.js:15:1)
   at __webpack_require__ (http://localhost:4200/inline.bundle.js:55:12)
   at eval code (eval code:15:1)
   at ../../../../../src/app/admin-layout/admin-layout.module.ts (http://localhost:4200/admin-layout.module.chunk.js:7:1)
   at __webpack_require__ (http://localhost:4200/inline.bundle.js:55:12)",
      message: "Uncaught (in promise): TypeError: Unable to get property 'call' of undefined or null reference
TypeError: Unable to get property 'call' of undefined or null reference
   at __webpack_require__ (http://localhost:4200/inline.bundle.js:55:12)
   at eval code (eval code:15:1)
   at ../../../../../src/app/admin-layout/change-password/change-password.component.ts (http://localhost:4200/admin-layout.module.chunk.js:59:1)
   at __webpack_require__ (http://localhost:4200/inline.bundle.js:55:12)
   at eval code (eval code:6:1)
   at ../../../../../src/app/admin-layout/admin-layout.routing.ts (http://localhost:4200/admin-layout.module.chunk.js:15:1)
   at __webpack_require__ (http://localhost:4200/inline.bundle.js:55:12)
   at eval code (eval code:15:1)
   at ../../../../../src/app/admin-layout/admin-layout.module.ts (http://localhost:4200/admin-layout.module.chunk.js:7:1)
   at __webpack_require__ (http://localhost:4200/inline.bundle.js:55:12)",
      name: "Error",
      promise: { },
      rejection: { },
      stack: "Error: Uncaught (in promise): TypeError: Unable to get property 'call' of undefined or null reference
TypeError: Unable to get property 'call' of undefined or null reference
   at __webpack_require__ (http://localhost:4200/inline.bundle.js:55:12)
   at eval code (eval code:15:1)
   at ../../../../../src/app/admin-layout/change-password/change-password.component.ts (http://localhost:4200/admin-layout.module.chunk.js:59:1)
   at __webpack_require__ (http://localhost:4200/inline.bundle.js:55:12)
   at eval code (eval code:6:1)
   at ../../../../../src/app/admin-layout/admin-layout.routing.ts (http://localhost:4200/admin-layout.module.chunk.js:15:1)
   at __webpack_require__ (http://localhost:4200/inline.bundle.js:55:12)
   at eval code (eval code:15:1)
   at ../../../../../src/app/admin-layout/admin-layout.module.ts (http://localhost:4200/admin-layout.module.chunk.js:7:1)
   at __webpack_require__ (http://localhost:4200/inline.bundle.js:55:12)
   at resolvePromise (eval code:809:25)
   at resolvePromise (eval co",
      Symbol()_g.7t813rgg29b: undefined,
      Symbol(observable)_i.7t813rgg29b: undefined,
      Symbol(rxSubscriber)_h.7t813rgg29b: undefined,
      task: { },
      zone: { }
   }

**Comment by TimvdLippe** [comment] 2018-06-17 15:37
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!

**Closed by TimvdLippe** 2018-06-17 15:37 UTC
Labels: ie
