### ISSUE TITLE
NotSupportedError on IE Edge

### ISSUE THREAD

**Issue by LostInBrittany** [webcomponents/webcomponentsjs#575] opened 2016-07-12 15:31 UTC
When testing my Polymer apps on Windows, I've stumped on a nasty error  with `webcomponents.js` on Microsoft Edge. When loading Polymer based apps, I get an error:

```
SCRIPT5022: NotSupportedError
webcomponents.js (1765,20)
```

And, of course, webcomponents aren't operational. Same error with `webcomponents-lite`

My Edge version: 
 
```
Microsoft Edge 38.14372.0.0
Microsoft EdgeHTML 14.14372
```

On IE 11 everything works.

I guess it's an error on Edge's side, but I'm not sure how to report it, and I think it deserves some analysis here...

**Comment by joozek78** [comment] 2016-08-10 10:28
I have the same error. My edge version is `38.14393.0.0` (latest at the time). @LostInBrittany did you manage to find any solution / workaround?

**Comment by LostInBrittany** [comment] 2016-08-10 20:37
Not yet, and it's quite a problem for me :(

**Comment by IntranetFactory** [comment] 2016-08-14 17:40
I'm also facing an `NotSupportedError` in Edge. I assume it's the same error with

Microsoft Edge 38.14393.0.0
Microsoft EdgeHTML 14.14393

![image](https://cloud.githubusercontent.com/assets/7462342/17650769/fa1661c0-6223-11e6-86f3-431a67ba8829.png)

**Comment by tigerhawkvok** [comment] 2016-08-17 19:42
Any work on this yet? It's not a small issue ...

**Comment by warpech** [comment] 2016-08-22 15:46
It is reproducible in Edge 14 with this four-liner:

```
<template is="dom-bind">
  <h1>Hello, {{name}}!</h1>
  <input value="{{name::input}}">
</template>
```

https://jsfiddle.net/warpech/gpw2ksdh/

Works everywhere except Edge 14.

Please help

**Comment by robdodson** [comment] 2016-08-23 00:57
Just curious, have you tried webcomponents-lite.js?

**Comment by tigerhawkvok** [comment] 2016-08-23 01:21
I have, yes.

**Comment by robdodson** [comment] 2016-08-23 01:40
@tigerhawkvok ok and it still produces the same error?

If you don't use `dom-bind` are you still able to reproduce it?

**Comment by tigerhawkvok** [comment] 2016-08-23 01:46
So proof on the import: 

https://github.com/AmphibiaWeb/amphibian-disease-tracker/blob/master/index.php#L40

This happens on both vulcanized and unvulcanized Polymer imports, with no explicit `dom-bind`ing otherwise

**Comment by robdodson** [comment] 2016-08-23 02:00
OK I've brought it to the team's attention

**Comment by warpech** [comment] 2016-08-23 07:34
>> Just curious, have you tried webcomponents-lite.js?

> I have, yes.

@robdodson On the other hand, my `dom-bind` example produces the error in Edge 14 only with webcomponents.js, not with webcomponents-lite.js.

- Error: `webcomponents.js` 0.7.22 + Polymer 1.6.1 - https://jsfiddle.net/warpech/gpw2ksdh/
- No error: `webcomponents-lite.js` 0.7.22 + Polymer 1.6.1 - https://jsfiddle.net/gpw2ksdh/5/

**Comment by keanulee** [comment] 2016-08-23 18:29
It looks like in the latest Edge (38), you can no longer specify `deep = false` when using [document.importNode](https://developer.mozilla.org/en-US/docs/Web/API/Document/importNode). This is done (at least once) [here](https://github.com/webcomponents/webcomponentsjs/blob/3ea23df8bc0f45d44fc903b706d379d7d50aba29/src/ShadowDOM/wrappers/Node.js#L260). You can verify this behavior on any page in Edge (e.g. the new tab page where `importNode` isn't wrapped:

![image](https://cloud.githubusercontent.com/assets/1319720/17904491/633c0478-6924-11e6-8a75-3d336074a3dd.png)

cc @justinfagnani since I think you are most familiar with the polyfills.

**Comment by keanulee** [comment] 2016-08-23 21:36
I updated my Windows 10 VM (through Windows Update) and don't seem to see the error with the demo that @warpech provided above (https://jsfiddle.net/warpech/gpw2ksdh/):

![image](https://cloud.githubusercontent.com/assets/1319720/17910653/a65519f6-693e-11e6-8ead-3470c90cacc8.png)

I suspect it's [this update](https://support.microsoft.com/en-us/kb/3176934), though the release notes aren't specific. @LostInBrittany @joozek78 @tigerhawkvok can you confirm?

**Comment by warpech** [comment] 2016-08-23 22:13
I have just installed:

- Update for Windows 10 Version 1607 for x64-based Systems ([KB3176936](https://support.microsoft.com/en-us/kb/3176936))
- Cumulative Update for Windows 10 Version 1607 for x64-based Systems ([KB3176934](https://support.microsoft.com/en-us/kb/3176934))

I can confirm that one of these updates fixes the problem.

Thanks @keanulee for noticing!

**Comment by LostInBrittany** [comment] 2016-08-24 00:31
I still have the problem, with Microsoft Edge 39.14905.1000.0.

I'm not sure of what are the last updated I have installed (I'm a Linux guy using Windows for testing) but my Windows tell me that it's up to date, i.e. no update pending...

**Comment by tigerhawkvok** [comment] 2016-08-24 06:10
@keanulee - Confirmed. Update while running `webcomponents-lite.js` fixes it (problem remains with `webcomponents.js`, but I'd meant to migrate away anyway for the project in question!).

**Comment by keanulee** [comment] 2016-08-24 21:28
Can confirm that the `NotSupportedError` is fixed with the recent Windows update - the VM on the left is a fresh image from https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/, the right is the same VM after the Windows update. Note that `document.importNode(document.createDocumentFragment(), false)` only works after, even though the Edge version number didn't change.

![image](https://cloud.githubusercontent.com/assets/1319720/17948477/db66f46c-6a05-11e6-9283-5bb7a8c1b857.png)

This behavior is used by the Shadow DOM polyfill, which is why `webcomponents-lite.js` works (since it doesn't include the Shadow DOM polyfill).

Please open a new issue if there's another issue and include an appropriate screenshot and/or test case.

**Closed by keanulee** 2016-08-24 21:28 UTC

**Comment by tomalec** [comment] 2016-11-03 15:24
Does anybody have an idea how to workaround this issue in SauceLabs? Especially, since WCT fails for errors thrown outside of tests.

**Comment by panuhorsmalahti** [comment] 2016-11-16 07:54
Note for anyone using the official Microsoft Edge VM images: you need to manually update Windows (which updates Edge), the currently supplied Edge in the VM has this bug.
