### ISSUE TITLE
[HTMLImports] IE11 sometimes fails to successfully import documents

### ISSUE THREAD

**Issue by sorvell** [webcomponents/webcomponentsjs#235] opened 2015-03-10 17:59 UTC
Yields the following error:

SCRIPT5022: HierarchyRequestError
File: importer.js, Line: 128, Column: 3

**Comment by azakus** [comment] 2015-03-10 18:01
Is there a particular import that you see that with? Got a hunch that this is an element being appended to `<html>` that isn't a `<body>` or `<head>`

**Comment by sorvell** [comment] 2015-03-10 18:52
We're hitting this, for example, when running the Polymer 0.8 tests using WCT. They will just randomly stop with this error. It's possible that this only occurs in the context of using WCT.

**Comment by garlicnation** [comment] 2015-03-11 07:06
The problem is in createHTMLDocument. It starts behaving really badly when called in fast enough succession. We might be able to fix this in the tests by adding some delay between running test suites, and I've reproduced the IE bug in https://github.com/garlicnation/crashie.

Chrome runs that html just fine, IE either crashes or ends up with a HierarchyRequestError.

**Comment by sorvell** [comment] 2015-03-11 16:28
is it enough to guarantee that IE does only one of these creates per task?
If so, we could probably adjust the imports polyfill to do this for IE.

**Comment by azakus** [comment] 2015-03-11 18:18
If we can't make createHTMLDocument stable enough, we can say that IE is only 100% supported when using vulcanize.

**Comment by IntranetFactory** [comment] 2015-03-11 18:36
I've tested the code from https://github.com/garlicnation/crashie with IE 11 on Win 8.1 and it neither crashed IE nor did it cause a HierarchyRequestError. But it's slow, and every ~4,000 items it stops for 3-5 seconds.

**Comment by garlicnation** [comment] 2015-03-13 21:36
The IE update from March 10, 2015 resolves this issue.

**Comment by brianblakely** [comment] 2016-09-20 17:10
I was experiencing this issue in 0.7.22.  Suddenly, it just stopped happening.

In `TemplateImpl.decorate` at this line: `template.content.appendChild(child);`

Also in `makeDocument` at this line: `var doc = document.implementation.createHTMLDocument(IMPORT_LINK_TYPE);`

**Comment by bedeoverend** [comment] 2016-11-03 23:15
FWIW I'm getting this issue as well. on v0.7.22 and IE11 on Windows8.1

**Comment by humana-fragilitas** [comment] 2016-11-07 20:35
@tjsavage could I ask you to let us know whether you plan to release a fix for this issue ? The *vulcanize everything* option may possibly be a choice for isolated applications but not for distributable components (e.g.: widgets to be included in third-party websites), per se meant to be freely assembled together and share resources via multiple imports. I am among those who are enthusiastically investing a considerable amount of hard work in crafting Polymer-based products, but most Web projects intended for general public consumption can't really afford to not fully and reliably support IE11: this is seriously blocking a huge amount of market-ready developments. Any help would be greatly appreciated.

**Comment by bedeoverend** [comment] 2016-11-11 05:05
+1 this one is a particularly large issue, even if it's not a fix, I'm struggling to break this issue down without more investigation, so currently it's causing our app to completely fail on IE11. Be fantastic if anyone has any ideas on the root cause of this.

**Comment by seaneking** [comment] 2016-11-22 03:04
bump. Any headway on this, or at least a sense of priority? Causing our (production) app to fail completely on IE11. Happy to help debug in any way possible, urgent issue for us.

Vulcanising isn't an option since we're serving a wc library consumed by non-wc folk, and forcing a cumbersome buildstep on them isn't tenable.

**Comment by tjsavage** [comment] 2016-11-30 21:36
Following up here - thanks all for the comments. We're aware of this bug and it's definitely a nasty one.

We're just starting to re-write the HTML Imports polyfill overall, to make it more cross-browser compatible particularly with Custom Elements v1 implementations that are shipping or soon-to-ship. It will be most feasible to fix this issue as part of that effort. The timing should be similar - it's starting right now, and we want to get the new version of the Imports polyfill out ASAP, ready before the Polymer 2.0 release early next year.

**Comment by bedeoverend** [comment] 2016-11-30 21:57
Thanks very much for follow up @tjsavage - look forward to testing out the new polyfill. I'd assume it will be able to run alongside webcomponentsjs v0, given v0 does feature detect?

**Comment by kapouer** [comment] 2017-01-22 11:38
How about [cloning a single disconnected document](https://github.com/garlicnation/crashie/pull/1) ? It seems to be working nicely on the version of IE11 that is known to crash. (tested with browserstack's IE11 on windows 7).

**Comment by kiancross** [comment] 2017-08-31 16:09
@tjsavage Is there any update on this?

**Comment by kiancross** [comment] 2017-08-31 20:01
Are there any fixes for this that don't involve upgrading to the new version of WebComponents Polyfil, as I beleive this version doesn't Polyfill Polymer 1.0. Currently we're not in a situation where we can upgrade to 2.0. If someone could outline the issue I would try to implement a solution.

@kapouer You're fix didn't seem to work for me.

**Comment by kapouer** [comment] 2017-09-01 08:36
@kiancross that's odd did you really try by loading the file from the create-html-document-polyfill project ?

**Comment by kiancross** [comment] 2017-09-14 17:53
@kapouer I added the `index.js` file from the project and then kept getting `WrongDocumentError` instead.

**Comment by TimvdLippe** [comment] 2018-06-17 16:09
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!

**Closed by TimvdLippe** 2018-06-17 16:09 UTC
