### ISSUE TITLE
v.2.1.x breaks style element

### ISSUE THREAD

**Issue by bjornwiberg** [webcomponents/webcomponentsjs#1035] opened 2018-10-15 14:17 UTC
v.2.0.4 the style tags in the component renders fine.

after v.2.1.x the styles elements have classes added to them and are rendered as inline text and breaks the design.

v.2.0.4
![image](https://user-images.githubusercontent.com/3403377/46956406-926b2500-d095-11e8-809f-0d5310f86530.png)

v.2.1.3
![image](https://user-images.githubusercontent.com/3403377/46956355-6bacee80-d095-11e8-8f94-9a4d4c4530ba.png)

**Comment by bjornwiberg** [comment] 2018-10-16 05:39
I don't really get the point to put a component specific styles in the header, cant we just travel with "outside" css into the component with `:host` selector?

We try to achieve independent styled components where we can allow specific styles to affected from with custom properties from `:host`

Is this breaking change introduced in the minor release of v.2.1.x?

Can ShadyCss be useful in this case?

**Comment by bjornwiberg** [comment] 2018-10-16 08:12
this is how we built our component https://github.com/qlik-oss/core-api-insights/blob/master/src/components/app-bar/ai-app-bar.js

**Comment by TimvdLippe** [comment] 2018-10-16 10:57
> I don't really get the point to put a component specific styles in the header, cant we just travel with "outside" css into the component with :host selector?

Sorry, my previous comment might be unclear. To clarify: you author CSS in your element. However, after that **ShadyCSS** should move the styles to head, after transformation. E.g. I was confused as to why **ShadyCSS** was not doing that.

Looking at your source code, that all seems fine. I see you are using `lit-html`, which might be the issue. @justinfagnani do you maybe have an idea what is going wrong here?

**Comment by azakus** [comment] 2019-06-07 21:32
Closing as a duplicate of making a more seamless ShadyCSS polyfill.

**Closed by azakus** 2019-06-07 21:32 UTC
