### ISSUE TITLE
Rename repo and npm package to "polyfills"

### ISSUE THREAD

**Issue by justinfagnani** [webcomponents/webcomponentsjs#1055] opened 2018-12-27 00:24 UTC
Since this repo/package only contains polyfills, and the name `@webcomponent/webcomponentsjs` is both long and hard to remember (which one has the 'js'?), we should consider renaming it to simply "polyfills".

We should also simplify the names of the scripts so that altogether we have shorter, simpler, easier to type and remember names, ie:

- `@webcomponents/polyfills/loader.js`
- `@webcomponents/polyfills/bundle.js`
- `@webcomponents/polyfills/custom-elements-es5-support.js`

**Comment by abdonrd** [comment] 2019-01-12 13:13
I really like the idea!

**Comment by azakus** [comment] 2019-06-07 19:19
Duplicate of webcomponents/polyfills#45

**Closed by azakus** 2019-06-07 19:19 UTC
