### ISSUE TITLE
webcomponents.js + angular2's es6-shim causes Uncaught RangeError

### ISSUE THREAD

**Issue by robdodson** [webcomponents/webcomponentsjs#261] opened 2015-03-28 15:16 UTC
I've created a small sample project based on the Angular2 Quickstart.

https://github.com/robdodson/angular2-webcomponentsjs-bug

It seems if you include `webcomponents-lite.js` or `webcomponents.js` you'll get an Uncaught RangeError.

If you turn on 'Pause on Exceptions' and use the async flag in the devtools you can track the call stack back to a method called `zoneBoundFn` inside of Angular's `es6-shim.js`. I may be wrong, but it looks like in the body of this function, the `fn` variable is the function itself, and it's calling it over and over:

```
// line 29866
return zone.run(fn, this, arguments);
```

The question is why is the inclusion of `webcomponents.js` causing it to get stuck in this state?

cc @justinfagnani

**Comment by addyosmani** [comment] 2015-03-30 18:08
Hey Rob. I was unable to get your demo to build (tried the quickstart directory). Is it possible to get it built/hosted on gh-pages so we can try to repro the issue?

Digging into..

```js
Zone.prototype = {
  constructor: Zone,

  fork: function (locals) {
    this.onZoneCreated();
    return new Zone(this, locals);
  },

  bind: function (fn, skipEnqueue) {
    skipEnqueue || this.enqueueTask(fn);
    var zone = this.fork();
    return function zoneBoundFn() {
      return zone.run(fn, this, arguments);
    };
  },
```

This seems to be throwing errors when paired with `setInterval`: https://github.com/angular/angular/issues/1050 or `setTimeout`: https://github.com/angular/angular/issues/1050. I wonder if we're running into some race conditions here.

Does Angular2 work fine with native Web Components?

**Comment by robdodson** [comment] 2015-03-30 18:30
Yeah it looks like this is an Angular2 issue. Things seemed to work fine so long as I didn't include `webcomponents.js`

**Comment by addyosmani** [comment] 2015-03-30 21:50
Reproduced the issue Rob was seeing. Almost certain this is an upstream issue with Angular2.

**Comment by addyosmani** [comment] 2015-03-31 15:13
@robdodson Are you okay with us closing this in favor of it being addressed in Angular?

**Comment by robdodson** [comment] 2015-03-31 15:47
Yep!

**Closed** 2015-03-31 16:03 UTC
Labels: question

**Comment by justinfagnani** [comment] 2015-04-01 03:11
Do we have an issue on Angular yet?

**Comment by robdodson** [comment] 2015-04-01 04:35
Addy linked to a couple tickets. We could open a new one if you think it
would help?

**Comment by justinfagnani** [comment] 2015-04-01 06:48
Ah... no those are good!

**Comment by webdevinci** [comment] 2016-03-16 20:59
A year later... I am having this same issue in Angular 2 beta. @addyosmani , it looks like you were on to something with the race condition; I have a timeout in my code that uses geolocate api, and I am getting the following:

TypeError: Cannot read property 'apply' of undefined
    at arguments.(anonymous function) (http://10.166.137.196:8100/build/js/app.bundle.js:1516:24)
    at Zone.run (http://10.166.137.196:8100/build/js/app.bundle.js:1161:18)
    at Zone.run (http://10.166.137.196:8100/build/js/app.bundle.js:17555:43)
    at zoneBoundFn (http://10.166.137.196:8100/build/js/app.bundle.js:1134:20)BrowserDomAdapter.logError @ app.bundle.js:33874ExceptionHandler.call @ app.bundle.js:7857(anonymous function) @ app.bundle.js:16983NgZone._notifyOnError @ app.bundle.js:17642collection_1.StringMapWrapper.merge.onError @ app.bundle.js:17537run @ app.bundle.js:1164(anonymous function) @ app.bundle.js:17555zoneBoundFn @ app.bundle.js:1134
app.bundle.js:1516 Uncaught TypeError: Cannot read property 'apply' of undefined 

The only other part I'm thinking may cause this is the fact that I use .bind() method to bind the scope of a the geolocation.getCurrentPosition's callback, and I noticed through debugger that a 'bind' function is being called in angular (or es6 shim).

Going to find a work around for now, but this seems to still be an issue

**Comment by robdodson** [comment] 2016-03-16 21:41
Just curious have you tried using webconpinents-lite.js?
