### ISSUE TITLE
README: native Shadow DOM is not available in Safari 10.0.3

### ISSUE THREAD

**Issue by mkutny** [webcomponents/webcomponentsjs#748] opened 2017-03-22 22:28 UTC
It is stated in the README that `webcomponents-hi-ce.js` will be loaded for Safari 10 but (I guess due to #691) the `loader` now loads `webcomponents-hi-sd-ce.js` for 10.0.3.

At the same time, it loads just `webcomponents-hi.js` for the TP 26.

I realize it's in flux and quickly changing, maybe use version ranges?

**Comment by TimvdLippe** [comment] 2018-06-17 15:59
We removed this reference from the README and I think this is working as intended now. Therefore I am closing this issue.

**Closed by TimvdLippe** 2018-06-17 15:59 UTC
